---
- name: "installing apache on localhost"
  become: true
  apt:
    name: 
      - apache2
    state: latest
    update_cache: yes

- name: "Install index file"
  copy: 
    src: index.html
    dest: /var/www/html/index.html
    backup: yes
    