version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  myjob1:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      docker:
        - image: amazon/aws-cli
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command

    # Exercise: Config and Deployment
  configure_infrastructure: 
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
              # You can get this ID in the section where you registered the SSH Key
              fingerprints: ["4b:8e:1f:13:a7:a0:5f:cb:22:cb:2b:77:d3:7c:88:e4"] 
      - run:
          name: Install Ansible
          command: |
            # install the dependencies needed for your playbook
            apk add --update ansible 
      - run:
          name: Run Playbook and Configure server
          command: |
            # Your command
            ansible-playbook -i inventory.txt main-remote.yml
  # Exercise: Smoke Testing
  smoke_test:
  docker:
    - image: alpine:latest
  steps:
    - run: apk add --update curl
    - run:
        name: smoke test
        command: |
          URL="https://blog.udacity.com/"
          # Test if website exists
          if curl -s --head ${URL} 
          then
            return 0
          else
            return 1
          fi

# Sequential workflow
workflows:
  # Name the workflow
  my_Workflow:
    jobs:
      - myjob1
      - configure_infrastructure
      # smoke_test
      - smoke_test
