version: 2.1
orbs:
  aws-cli: circleci/aws-cli@2.0.3
commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}
jobs:
  myjob1:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: echo "hello world"
  configure_infrastructure:
    docker:
      - image: 'python:3.7-alpine3.16'
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - '4b:8e:1f:13:a7:a0:5f:cb:22:cb:2b:77:d3:7c:88:e4'
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main-remote.yml
  smoke_test:
    docker:
      - image: amazon/aws-cli
    steps:
      - run:
          name: Test job
          # command: return 1
          command: return 0
      - destroy_environment
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
              --region us-east-1
workflows:
  my_Workflow:
    jobs:
      - myjob1
      - configure_infrastructure
      - create_infrastructure
      - smoke_test